
CURRENCYLAYER_TOKEN = '71d0cbffaabea986fb4c860aab48d902'

# in case you do use this live my twitter account is @argparse
TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_SECRET = ''


TWILIO_SID = ''
TWILIO_TOKEN = ''
TWILIO_FROM_NUMBER = ''
TWILIO_TO_NUMBER = ''
